# Generated by Django 5.1.7 on 2025-03-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_id", models.CharField(max_length=255)),
                ("discord_username", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Kingdom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("continent", models.PositiveSmallIntegerField(default=0)),
                (
                    "discord_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kingdoms",
                        to="bot_discord.discorduser",
                    ),
                ),
            ],
        ),
    ]
